#!/usr/bin/env python3
"""
Deploy Vapi Assistant — System Prompt + Server URL Update
==========================================================
Updates the Big Reef Personal Vapi assistant with:
  1. Enhanced system prompt (CRM lookups + calendar scheduling)
  2. Server URL pointing to the Agentic OS tunnel

Usage:
  python3 deploy_vapi.py                    # Auto-deploy
  python3 deploy_vapi.py --dry-run          # Show what would change
  python3 deploy_vapi.py --assistant-id ID  # Override assistant ID
"""

import json
import os
import subprocess
import sys
import urllib.request

# ── Config ──────────────────────────────────────────────────
ASSISTANT_ID = os.environ.get("VAPI_ASSISTANT_ID", "9b00342e-1951-4bd0-b4a5-5ca4c9827bd0")

# Try to read VAPI_API_KEY from multiple sources
VAPI_API_KEY = os.environ.get("VAPI_API_KEY", "")
if not VAPI_API_KEY:
    # Try .env file in various locations
    for env_path in [
        "/home/hermeswebui/.hermes/.env",
        "/home/hermes/.hermes/.env",
        os.path.expanduser("~/.hermes/.env"),
    ]:
        if os.path.exists(env_path):
            with open(env_path) as f:
                for line in f:
                    if line.startswith("VAPI_API_KEY"):
                        VAPI_API_KEY = line.split("=", 1)[1].strip().strip("'\"")
                        break
            if VAPI_API_KEY:
                break

# Try to get the current Agentic OS tunnel URL
AGENTIC_OS_TUNNEL = os.environ.get("AGENTIC_OS_TUNNEL", "")
if not AGENTIC_OS_TUNNEL:
    # Check if cloudflared is running and get its URL
    import subprocess
    try:
        result = subprocess.run(
            ["grep", "-o", "https://[a-z0-9.-]*\\.trycloudflare\\.com", "/proc/*/fd/1"],
            capture_output=True, text=True, timeout=5, shell=True,
        )
        urls = result.stdout.strip().split("\n")
        if urls and urls[0]:
            AGENTIC_OS_TUNNEL = urls[0].strip()
    except Exception:
        pass

if not AGENTIC_OS_TUNNEL:
    # Fallback to the last known tunnel
    AGENTIC_OS_TUNNEL = "https://counting-combo-warren-baptist.trycloudflare.com"
VAPI_API_BASE = "https://api.vapi.ai"

# ── Enhanced System Prompt ─────────────────────────────────
SYSTEM_PROMPT = """You are Big Reef's personal voice assistant for Montefiore Urology. You help callers with three things:

## 1. AUTHENTICATION
Start every call by asking for the caller's full name.
- POST SERVER_URL/auth with {"name": NAME, "pin": PIN}
- If ok: Read the greeting from the response. Then ask what they need.
- If wrong: max 3 retries, then ask them to call the office.

## 2. CRM LOOKUPS
Callers can ask about anyone in the system. Use these endpoints:

**Search for a person:** GET SERVER_URL/crm/search?q=NAME
Returns their name, role, email, phone, department.
Example: "Who is Dr. Sankin?" → search "Sankin" → returns Alex Sankin, Faculty, aaboumoh@montefiore.org

**List faculty:** GET SERVER_URL/crm/faculty
**List residents:** GET SERVER_URL/crm/residents

**Look up by email:** GET SERVER_URL/crm/contact?email=EMAIL

**Check who's on call today:** GET SERVER_URL/schedule/today
Returns who's covering Moses, Wakefield, and Weiler today.

**Check a person's schedule:** GET SERVER_URL/schedule/person?name=NAME
Returns their call assignments.

## 3. SCHEDULE MEETINGS
When Big Reef says "schedule a meeting with [person] about [topic] on [date/time]":

1. Look up the person in CRM to get their email
2. Confirm the details: "Schedule a [duration]-minute meeting with [name] on [date] at [time] about [topic]?"
3. If confirmed, POST to SERVER_URL/meeting with:
   {
     "title": "Meeting topic",
     "date": "YYYY-MM-DD",
     "start_time": "HH:MM",
     "duration_minutes": 30,
     "attendees": ["person@montefiore.org"],
     "description": "Brief description",
     "location": "Optional location"
   }
4. The system sends a meeting invitation. @montefiore.org attendees will get it through Outlook which generates Zoom codes automatically.
5. Confirm to Big Reef: "Meeting scheduled. Invite sent to [attendees]. Zoom details will be generated by Outlook."

## CRITICAL RULES
- Never ask for PIN twice.
- Never share one person's data with another caller.
- For meeting scheduling, always read back the details and get confirmation before sending.
- Never guess email addresses — always look them up in CRM first.
- If CRM search returns no results, say "I couldn't find them in the Montefiore system."
"""


def vapi_request(method: str, path: str, data: dict = None):
    """Make a Vapi API request."""
    url = f"{VAPI_API_BASE}{path}"
    headers = {
        "Authorization": f"Bearer {VAPI_API_KEY}",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        err_body = e.read().decode() if e.fp else ""
        return {"error": f"HTTP {e.code}: {err_body}"}
    except Exception as e:
        return {"error": str(e)}


def get_current_assistant():
    """Get the current assistant config."""
    return vapi_request("GET", f"/assistant/{ASSISTANT_ID}")


def build_update_payload() -> dict:
    """Build the assistant update payload."""
    return {
        "model": {
            "provider": "openai",
            "model": "gpt-4o",
            "temperature": 0.7,
            "messages": [
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                }
            ],
        },
        "server": {
            "url": f"{AGENTIC_OS_TUNNEL}/api/vapi",
            "timeoutSeconds": 20,
        },
        "firstMessage": "Thank you for calling Montefiore Urology. Before I help you, I need your full name and 4-digit PIN.",
    }


def deploy(dry_run: bool = False):
    """Update the Vapi assistant."""
    if not VAPI_API_KEY:
        print("❌ VAPI_API_KEY not set. Export it or set in .env")
        sys.exit(1)

    print(f"📋 Assistant ID: {ASSISTANT_ID}")
    print(f"🔗 Server URL:   {AGENTIC_OS_TUNNEL}/api/vapi")
    print()

    # Get current state
    current = get_current_assistant()
    if "error" in current:
        print(f"❌ Failed to get current assistant: {current['error']}")
        print("   Check: API key, assistant ID, network")
        sys.exit(1)

    print(f"✅ Current assistant: {current.get('name', 'Unknown')}")
    print(f"   Model: {current.get('model', {}).get('model', 'Unknown')}")
    print()

    if dry_run:
        print("🔍 DRY RUN — Would update with:")
        print(json.dumps(build_update_payload(), indent=2))
        return

    # Apply update
    payload = build_update_payload()
    result = vapi_request("PATCH", f"/assistant/{ASSISTANT_ID}", payload)

    if "error" in result:
        print(f"❌ Update failed: {result['error']}")
        sys.exit(1)

    print(f"✅ Vapi assistant updated successfully!")
    print(f"   Name: {result.get('name', ASSISTANT_ID)}")
    print(f"   Server URL: {AGENTIC_OS_TUNNEL}/api/vapi")
    print()
    print("📞 Next steps:")
    print(f"   1. Verify the Cloudflare tunnel for Agentic OS is running")
    print(f"   2. Restart Agentic OS server to pick up the Vapi bridge module")
    print(f"   3. Test: call +1 (979) 234-0498 and ask 'who is on call today'")
    print(f"   4. Test: 'schedule a meeting with Dr. Sankin on Tuesday at 2pm'")


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    deploy(dry_run=dry_run)
